### PR TITLE
Support CRX3 bodies

### PR DESCRIPTION
**Pull request by sean-adams**
Chrome has switched to the new CRX3 extension format, which has slightly different (and dynamic) header lengths.
This PR
- doesn't fail when encountering a non '2' version number, and
- successfully extracts the ZIP body from a CRX3 file

### CODE REVIEW

**Comment by sean-adams** [comment]
While I know this library hasn't been published in 4 years and this PR may seem out of the blue :smile: the library is still actively being relied on by https://github.com/mozilla/addons-linter , which is relied on by a whole host of other Mozilla extension tools.

**Comment by shyiko** [comment]
Hey Sean. Thanks for the PR! My only concern is unused rawHeader - https://github.com/shyiko/node-crx-parser/pull/2/files#diff-1fdf421c05c1140f6d71444ea2b27638R30 and no tests. Other than that it's ready to merge.

Any chance you would be willing to either parse [the header](https://github.com/bmatthews68/crx-maven-plugin/issues/14#issuecomment-478821485) (preferable) or to comment it out?

**Comment by Rob--W** [comment]
@shyiko The only two dependencies of this library don't use the public key at all. For simplicity, how about removing the public key "parser" all together, and bumping the major version?

And while you are updating the library anyway, replace the deprecated `new Buffer` methods.

**Comment by sean-adams** [comment]
@Rob--W happy to see you here, I don't have Protobuf experience and had been trying to wrap my mind around your relevant crxviewer code to try to attack the header component of this.

@shyiko I can update this PR today to remove the unused rawHeader, add a CRX3 test, and update the `new Buffer` calls, but parsing the header will take some more attention / time. Also thanks for the quick response on all this!

**Comment by jarodsmk** [comment]
@sean-adams Just stumbled across your conversation here!

@Rob--W - I was looking at your code over on [crxviewer](https://github.com/Rob--W/crxviewer) and saw how you were parsing the versions of the CRX files, in order to solve an issue present on [webext-compat-tool](https://github.com/mozilla/webext-compat-tool/issues/14).

I'm considering creating another package to handle this better (as well as further CRX versions which may be added in the future). It seems like this package isn't being maintained as there hasn't been much activity on the master branch recently.

Any thoughts on this from your sides? Cheers

**Comment by shyiko** [comment]
Thank you! Merging in :+1:

**Comment by sean-adams** [comment]
Thanks @shyiko !

@jarodsmk @Rob--W maybe let's continue that conversation over at https://github.com/mozilla/addons-linter/issues/2621 ?

**Comment by Rob--W** [comment]
@jarodsmk The package here seems to be maintained (as evidenced by pull requests being accepted).

As mentioned before, this package isn't widely used, only by one of the author's other packages, and by Mozilla's addons-linter. So to keep it simple, the signature extractor should not be needed.

@shyiko Since the package cannot reliably extract the signature from the CRX file (CRX3 being the modern version), could you remove the header extraction functionality from this package? Otherwise people that rely on it and test with CRX2 files would see working functionality, but encounter broken functionality when CRX3 files are used. Since the removal of signatures is a big change, bump the version to `0.2.0` (according to semver conventions).

**Comment by jarodsmk** [comment]
Huzzah! Thanks for merging this in @shyiko, thanks for the work @sean-adams :)

@Rob--W - Perfect. This should (somewhat) resolve the issues over at Mozilla's Webextension compatibility checker. 

Edit: Will give it some more testing when I can.

Thanks all! 💯

**Pull request merged**
